# Generated by Django 2.1 on 2018-12-30 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('dob', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=400)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('year_in_college', models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level'), ('600', '600 Level')], default='', max_length=3)),
                ('college', models.CharField(choices=[('ABSU', 'Abia State University, Uturu, Abia State'), ('EBSU', 'Ebonyi State University, Abakaliki'), ('UNILAG', 'University of Lagos, Idi Araba, Lagos State'), ('OAU', 'Obafemi Awolowo University, Ile Ife, Osun State'), ('UNIPORT', 'University of Port-Harcourt, Rivers State'), ('UDUSOK', 'Usman Dan Fodiyo University, Sokoto, Sokoto State'), ('UI', 'University of Ibadan, Oyo State'), ('UNILORIN', 'University of Ilorin, Kwara State'), ('UNICAL', 'University of Calabar, Cross River State'), ('LASU', 'Lagos State University, Ikeja, Lagos State'), ('AAU', 'Ambrose Alli University, Ekpoma, Edo State'), ('UNIJOS', 'University of Jos, Plateau State'), ('BUK', 'Bayero University, Kano, Kano State'), ('OOU', ' Olabisi Onabanjo (formerly Ogun State) University, Ago Iwoye, Ogun State'), ('IMSU', 'Imo State University, Owerri, Imo State'), ('MADONNA', 'Madonna University Okija'), ('UNIBEN', 'University of Benin, Benin-City, Edo State'), ('OBA OKUNADE', 'Oba Okunade College of Health Sciences Igbinedion University Okada, Benin -City, Edo State'), ('UNN', 'University of Nigeria, Ozara-Ituku. Enugu State'), ('UNIZIK', 'Nnamdi Azikiwe University, Nnewi, Anambra State'), ('ABU', 'Ahmadu Bello University Zaria, Kaduna State'), ('UNIMAID', 'University of Maiduguri, Borno State'), ('DELSU', 'Delta State University, Abraka, Delta State'), ('ESUT', 'Enugu State University of Science and Technology, Enugu, Enugu State'), ('UNIUYO', 'University of Uyo, Uyo, Cross River State'), ('BINGHAM UNI', 'Bingham University Karu, Nasarawa.State'), ('NIGER-DELTA UNI', 'Niger Delta University, Wilberforce Island, Bayelsa State'), ('BENSU', 'Benue State University, Makurdi, Benue State'), ('BABCOCK', 'Babcock University Ilishan-Remo, Ogun State'), ('UNIABJ', 'University of Abuja'), ('AFE-BABALOLA', 'Afe Babalola University Ado-Ekiti, Ekiti State')], default='', max_length=15)),
                ('following', models.ManyToManyField(blank=True, null=True, related_name='follows', to='users.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
