# Generated by Django 2.1 on 2018-11-18 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181117_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='avatar',
        ),
    ]
