# Generated by Django 2.1 on 2018-12-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_profile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
