# Generated by Django 2.1 on 2018-12-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_profile_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='followers',
            new_name='follower',
        ),
    ]
