# Generated by Django 2.1 on 2018-12-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_profile_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='profile',
            name='year_in_college',
            field=models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level'), ('600', '600 Level')], default='none', max_length=3),
        ),
    ]
