# Generated by Django 2.1 on 2018-12-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
