# Generated by Django 2.1 on 2018-12-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
