# Generated by Django 2.1 on 2018-12-14 22:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0011_auto_20181212_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_commented',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
