AWS_ACCESS_KEY_ID = 'AKIAJOC3BPCF6BDL6U6A'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'blermo'
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME


SECRET_KEY = '6(7cx+^)a@2wwxq+h$=2l*+r5d03&+j4!v9@ym_g*u6!4ej2jp'
