AWS_ACCESS_KEY_ID = 'AKIAIMXCTUTV3JDEWCCA'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'blermo'
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

SECRET_KEY = '6(7cx+^)a@2wwxq+h$=2l*+r5d03&+j4!v9@ym_g*u6!4ej2jp'
