# Generated by Django 2.1.2 on 2018-11-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='ewu', max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='hello'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='kkgkgkgkgkgkgkggkgk', max_length=20),
        ),
    ]
